# Site settings
title: Data Scientist
email: tshikovhi.elle466@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Driven and aspiring individual who has great analytical and problem-solving skills. 
              Able to work independently as well as part of a team, able to produce creative and innovative ideas. 
              With strong programming skills  i love  being challenged and learning which contribute to my self development. 
              I am passionate about all thing Data and technology ,finding meaningful insights and executing excellent AI driven solutuions .             It will appear in your document head meta (for Google search results) and in your feed.xml site description."
code skils: "Python,MATLAB, OCTAVE, SAS, and SQL"
skills: "Data Engineer ,ML Engineer,Business Intelligent Developer/Analyst,Data Analyst"
meta_author: Tshikovhi Elelwani

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 		bc2518  #78180f
  primary-rgb: "0, 0, 0" #"120, 24, 15"
  secondary:  0a0a0a #040225
  secondary-dark: ececec 	#0a0a0a

# Footer settings
footer:
  copyright: Elelwani Tshikovhi
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/elelwani-tshikovhi-152089a0/
  - title: github
    url: https://github.com/ElelwaniTshikovhi

# Postal address (add as many lines as necessary)
address:
  - line: 464 Meadowlands Ext 8
  - line: Soweto,Johannesburg , South Africa

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
